name: wha
description: World Health Aid telemedicine project
publish_to: none
version: 1.0.0+2
environment: { sdk: '>=2.12.0 <3.0.0' }
dependencies:
  flutter: { sdk: flutter }
  get: ^4.3.8
  http: ^0.13.5
  sqflite: ^2.0.0+4
  google_fonts: ^2.1.0
  connectivity_plus: ^2.0.2
  card_swiper: ^1.0.4
  shared_preferences: ^2.0.8
  avatar_glow: ^2.0.1
  youtube_player_flutter: ^8.0.0
  flutter_spinkit: ^5.1.0
  country_code_picker: ^2.0.2
  sms_autofill: ^2.2.0
  flutter_google_places: ^0.3.0
  image_picker: ^0.8.4+4
  file_picker: ^5.1.0
  shimmer: ^2.0.0
  url_launcher: ^6.0.15
  jitsi_meet: ^4.0.0
  flutter_vibrate: ^1.3.0
  flutter_ringtone_player: ^3.1.1
  screenshot: ^1.2.3
  image_gallery_saver: ^1.7.1




  font_awesome_flutter: ^9.2.0
  flutter_screenutil: ^5.0.0+2
  fluttertoast: ^8.0.7
  intl: ^0.17.0
  lottie: ^1.0.1
  crypto: ^3.0.1
  convert: ^3.0.0
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/silver_package.jpg
    - assets/

  fonts: [ ]
